### PR TITLE
console: fix /give command giving duplicate items

### LINKED ISSUE #1463: Bug: /give 10 medi gives 20 small medipacks and 20 large medipacks
While it's OK to give both small and large medipacks since the command is ambiguous, it's not OK to hand them out twice like so:

363041700-a569bf1e-7433-4918-ae80-cc20d926b56e

The bug occurs because `Object_IdsFromName` does not ensure unique matches, e.g. if the input matches two aliases for the same object, the object appears twice in the returned value.

@aredfan can you please try and find out what was the version that introduced this bug?

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Uses https://github.com/LostArtefacts/libtrx/pull/21
Resolves #1463.

### CODE REVIEW

**Comment by aredfan** [comment]
@rr- Any chance of a test build? 🤞

**Comment by rr-** [comment]
Sure, here it is: https://home.wind.garden/serve/pub/TR1X-4.3-13-gc72a1ab-Windows.zip

**Comment by aredfan** [comment]
The `/give` command for [weapon] ammo, clips, shells, keys and medi is providing the correct number as expected.

I may have found an issue when using the command `/give key` in Tomb of Tihocan. Note the second line. 



Apart from that, LGTM.

**Review by aredfan — APPROVED** [review]

**Comment by walkawayy** [comment]
> The `/give` command for [weapon] ammo, clips, shells, keys and medi is providing the correct number as expected.
> 
> I may have found an issue when using the command `/give key` in Tomb of Tihocan. Note the second line.
> 
> 
> 
> Apart from that, LGTM.

Interesting yes I see that too. The same issue with the weird log happens in Cistern, City of Khamoon, Obelisk of Khamoon, and Sanctuary of the Scion, and Natla's Mines. These are all levels that have keys as key items which I'm guessing is causing the confusion.

Results of `give ke` are normal:
image

Results of `give key` are weird though:
image


Natla's Mines also gives a key that is unused and unnamed, but I'm guessing that's more to do with an issue in the level file that has a leftover key.

image

`give key` in Atlantis log output prints 4 messages about no keys. My guess is that relates to the 4 puzzle item slots per level?

image



I don't see any issues with the actual functionality. The game gives the right items, it's just the console log that's acting a little weird.

**Comment by rr-** [comment]
Fixed this as well: https://home.wind.garden/serve/pub/TR1X-4.3-14-g08a8705-Windows.zip

**Review by walkawayy — APPROVED** [review]
Nice looks fixed to me!

**Pull request merged**
