### PR TITLE
gfx: add an option to render using framebuffers

### LINKED ISSUE #114: Suggestion: Change Renderer Behaviour
Changing Resolution doesnt change the resolution of the back buffer (it is the same size as device's main resolution)
This means that even though the Resolution is set as 800x600, the Renderer still renders as 1920x1080 (my native resolution).

What the renderer does instead is a bit complex.
The vertices are snapped to the "pixels" of the resolution in the settings which results in heavily distorted models.
I noticed that the game isn't rendered in my full resolution though. The vertical resolution stays the same (1080), while the horizontal resolution changes with the resolution i set.

Here is a screenshot of original TombATI (custom resolution of 160x120, extreme case but for showcasing purposes) and reproducible with Tomb1Main:
screenshot0003

Notice how the image is 1080px high, but the "resolution" of Lara is as if it is 160x120.

I'd expect to have a smaller frame buffer (160x120 in this case), i.e. rendering what you actually set in the settings.

I also noticed that the Title menu is rendered independently. Changing resolution does not affect the tile menu

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #114.

Add a new rendering mode that uses framebuffers and lets the player run the game at truly lower resolutions (which then get upscaled to window size, but this is fast).
For now the framebuffer upscaling filter is tied to the game filter, however, I'd like to introduce a separate setting for this in a follow-up pull request.

Testing this should involve changing the resolutions, changing the render mode, checking how this behaves with FMVs and pictures, and finally, screenshots. Screenshots made with render mode set to framebuffer should have the image size equal to the chosen resolution.

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
Works great for me. I tried changing between each mode and resolution and didn't see any issues. FMVs and screenshots also working/generating as expected.
One thing I did notice is that a lot of errors are being logged from `sampler.c` line 27 (log attached). I appreciate this may not be directly related, but thought it worth mentioning as the functions here now check for errors.
[Tomb1Main.log.txt](https://github.com/LostArtefacts/Tomb1Main/files/12565557/Tomb1Main.log.txt)

**Comment by walkawayy** [comment]
Works very well! Two minor things I noticed:

Flickering artifacts when switching resolutions in frame buffer mode (I don't think users will be changing this often, but wanted to mention) Also noticed after uploading maybe streaming the resolution change messes with OBS. But when you flip through resolutions you can notice text box artifacts and stuff:

https://github.com/LostArtefacts/Tomb1Main/assets/81546780/b0cb5dde-2f85-45ce-87a8-4f5059b4e286



Text of `Framebuffer` is overlapped with the arrow:
20230909_093542_Caves

**Comment by rr-** [comment]
I removed the errors in the logs as well as improved the UI. I'm really not sure how to fix the visual flicker, but IMO it's acceptable at this point.

**Review by lahm86 — APPROVED** [review]
LGTM

**Review by walkawayy — APPROVED** [review]
Ya I think the flickering is fine, I just wanted to mention it for awareness. Better than requiring a game reboot like some games lol.

**Pull request merged**
