### PR TITLE
console: move ui to libtrx

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

https://github.com/LostArtefacts/libtrx/pull/37

### CODE REVIEW

**Comment by aredfan** [comment]
The prior issues are now resolved, thank you. I've noticed a small issue - the blinking caret is slower now.

**Review by aredfan — APPROVED** [review]
The blinking caret LGTM. 👍

**Comment by lahm86** [comment]
I have text scale set at 0.8, and the console shows here. It moves further up the lower the value and can go off-screen if too high.
image

**Comment by rr-** [comment]
Fixed, but I can't say I like my solution. @lahm86 could you please take a look around the code, especially libtrx, and LMK if you see anything that I could've done better?

**Review by walkawayy — APPROVED** [review]
LGTM at all text scalings

**Comment by rr-** [comment]
> Fixed, but I can't say I like my solution. @lahm86 could you please take a look around the code, especially libtrx, and LMK if you see anything that I could've done better?

I've improved the APIs a bit and I'm a bit happier. There are still some design smells such as UI having to be initialized after the config or else reacting to text scaling changes will not work, or the config `change` events being fired by `Config_Write` calls, but I was unable to come up with a reasonable alternative. The widgets, especially the stack, should be in a good spot now, though.

**Review by aredfan — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]

**Pull request merged**
