### PR TITLE
Fix crashes related to live changing of save slots; support disabling save slots completely

### LINKED ISSUE #1954: TR1X bug: changing save slot count when the game is running is dangerous
Trying to use `/set save-slot` especially when looking at the savegame selector currently leads to crashes.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1954.

### CODE REVIEW

**Comment by rr-** [comment]
When issuing `/set save-slot 0` and later trying to save or load, the game should handle this gracefully by either allowing to restart the current level, or playing the game from scratch. This can be triggered from many contexts:
- Esc menu, navigate to the lower ring, open passport manually
- F5 quick save
- F6 quick load
- Title screen

I still am experiencing some crashes when trying to change live to slot count 0, but I'll get around this.

**Comment by rr-** [comment]
Should be good now.

**Comment by aredfan** [comment]
These steps trigger a crash:

1. `/set save-slot 25`
2. Go into the save dialog
3. Scroll down and highlight any save slot in the range of 21-25
4. `/set save-slot 20`

**Comment by rr-** [comment]
@aredfan thank you for thorough testing – should be fixed now.

**Review by aredfan — APPROVED** [review]

**Pull request merged**
