### PR TITLE
UI scale fix Patch

### LINKED ISSUE #643: Text backgrounds are 1 pixel short on 16:10 monitors
The darkened text background is 1 pixel short of reaching the text outline as seen on the left in this screenshot.

image

### PR DESCRIPTION
**Pull request by oziphantom**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [ ] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Posix reported a single pixel wide crack on the load game menu, when using PS1 mode, on a 16:10 monitor with a UI Scale of 1.5. So I just expanded the box by 1 on each side to close up and other cracks that may appear. This is a minor bug fix for an existing feature, so there's no changelog entry.

### CODE REVIEW

**Comment by rr-** [comment]
@walkawayy can you test this patch in various circumstances? Thanks.

**Comment by walkawayy** [comment]
I tried testing the new build at various resolutions at various scalings, and it looked good to me. I don't have a bunch of different monitor sizes though, only 16:9. I sent the build to Posix to see if it fixed his issue since he is on 16:10.

**Comment by Richard-L** [comment]
I tried it too and the issue is gone now.

**Comment by walkawayy** [comment]
Can you add a 2.12 milestone? I think this fix is good to go.

**Review by walkawayy — APPROVED** [review]

**Pull request merged**
