### PR TITLE
tr1/config-tool: small changes to the Italian translation

### PR DESCRIPTION
**Pull request by Kappa971**
#### Checklist

- [ ] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [ ] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Small changes to the Italian translation of TR1X ConfigTool.

I also updated the Italian translation of the game menus for TR1X 4.6.1: [TR1X4-6-1_TradITA.zip](https://github.com/user-attachments/files/18141438/TR1X4-6-1_TradITA.zip).
I hope someone starts working on the localization system and puts more emphasis on accessibility, because at the moment it is necessary to completely revise the scripts with each new version of TR1X, besides the fact that there are no subtitles for the in-game engine cutscenes (and it is not possible to add them).

### CODE REVIEW

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
> #### Checklist
> * [ ]  I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
> * [ ]  I have added a changelog entry about what my pull request accomplishes, or it is an internal change
> 
> #### Description
> Small changes to the Italian translation of TR1X ConfigTool.
> 
> I also updated the Italian translation of the game menus for TR1X 4.6.1: [TR1X4-6-1_TradITA.zip](https://github.com/user-attachments/files/18141438/TR1X4-6-1_TradITA.zip). I hope someone starts working on the localization system and puts more emphasis on accessibility, because at the moment it is necessary to completely revise the scripts with each new version of TR1X, besides the fact that there are no subtitles for the in-game engine cutscenes (and it is not possible to add them).

Can you describe your ideal workflow? We're considering two things:

1) Moving all the gameflow strings – UIs, item names, etc., to a separate JSON file. (Relatively easy). This would decouple level scripting from translating.
2) Bringing the game configuration entirely into the game itself. (Massive effort, won't happen anytime soon). This would reduce number of files translators need to work with.

As for the subtitles, recent advancements in TR2 rendering have brought us somewhat closer to this goal, but we currently have our hands full of other priorities at the moment so can't say anything for sure regarding this.

**Comment by Kappa971** [comment]
>     1. Moving all the gameflow strings – UIs, item names, etc., to a separate JSON file. (Relatively easy).
>        This would decouple level scripting from translating.

This would already be a good solution.
Does TR1X support displaying special characters (in the game menu)? In Italian they are usually: `à` `è` `é` `ì` `ò` `ù`. At the moment I wrote, for example, `à` as `a'` because I remember that in the past the accented character was not displayed correctly.

> As for the subtitles, recent advancements in TR2 rendering have brought us somewhat closer to this goal, but we currently have our hands full of other priorities at the moment so can't say anything for sure regarding this.

Okay, thanks.

**Review by lahm86 — APPROVED** [review]

**Comment by rr-** [comment]
> Does TR1X support displaying special characters (in the game menu)? In Italian they are usually: `à` `è` `é` `ì` `ò` `ù`. At the moment I wrote, for example, `à` as `a'` because I remember that in the past the accented character was not displayed correctly.

Yes, we made a big effort to support these characters and it's landed in the most recent stable!

**Comment by Kappa971** [comment]
> Yes, we made a big effort to support these characters and it's landed in the most recent stable!

I confirm that now it works:
TR1X 05_01_2025 12_59_25

**Pull request merged**
