### PR TITLE
TR2: add user controllable FOV

### LINKED ISSUE #2002: OG bug: FOV is interpreted as horizontal which causes cropping in widescreen

### LINKED ISSUE #2177: TR2: add ability to change the game FOV
Related to #2002.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [X] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

 I chose to always apply the vertical FOV instead of making it a setting like in TR1. Instead, I included TR2Main's PCX FOV feature. This is primarily important for the inventory ring and cutscenes, which have fixed FOV values that players can't adjust themselves. I've been careful not to break the cutscenes, but it would be helpful to have them reviewed.

### CODE REVIEW

**Comment by Richard-L** [comment]
Will try to do more testing after some sleep, but:
- What's TR2Main's PCX feature?
- Is there, or do you plan to enable, a way from the config tool, or in-game sunglasses settings, to set the PS1 FOV? This new FOV in the build is a definite improvement, but the ring menu and Lara with weapon equipped feel rather tiny to my PS1 eyes.

**Comment by rr-** [comment]
> Will try to do more testing after some sleep, but:
> 
> * What's TR2Main's PCX feature?

It slightly enlarges the game by using a different height option. I recommend enabling this.

> * Is there, or do you plan to enable, a way from the config tool, or in-game sunglasses settings, to set the PS1 FOV?

I read this as two questions, re: better UI – yes this is #1615, re: PS1 FOV – why not? But please do try the PCX FOV and LMK if it's different, ideally with screenshots of the title screen.

**Review by aredfan — APPROVED** [review]
Looks great! Thank you. 👍

**Comment by aredfan** [comment]
I did end up finding an issue after all.  It's possible for the `/set pcx` command to stop working after Lara uses a key on a keyhole. It can also happen with a puzzle hole.

1. `/play 12`
2. `/tp keyhole`
3. use the all items cheat
4. use the key
5. `/set pcx 0` or `/set pcx 1`

**Comment by Richard-L** [comment]
How do you enable PCX?

Did I miss it in the config tool?

**Comment by rr-** [comment]
> How do you enable PCX?
> 
> Did I miss it in the config tool?

For now, no UI for this – `/set` or the config file. I'll add that to the changelog. 
It won't make its way to the config tool – it's supposed to be easily changeable from the game, and we'll get to that in #1615 but I cannot work on everything at once.

**Review by lahm86 — COMMENTED** [review]
Looks great. My only thought would be to make the pcx setting enabled by default.

**Comment by rr-** [comment]
@aredfan @lahm86 fixed.
Also, found an issue where 3D pickups would pick up user FOV, which for extreme values would look really off. Fixed that as well.

I changed the order of the inventory ring initialization so it'd be good to test its interaction with game music, the spinout sound, and other side effects.

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]

**Comment by Richard-L** [comment]
> For now, no UI for this – `/set` or the config file. I'll add that to the changelog. It won't make its way to the config tool – it's supposed to be easily changeable from the game, and we'll get to that in #1615 but I cannot work on everything at once.

There's still no table anywhere with all possible console commands is there? I tried a couple and after some failures worked out how to turn PCX on/off. On seems to look like OG?

I also tried to set the FOV to 60 like you can in TR1X' config file, but I didn't manage to guess the right console command here.

Tbh the console is a little frustrating due to the intended guesswork, and due to it not being possible to type `/` on my keyboard. But it seems to work without it still.

**Comment by walkawayy** [comment]
Here's all the commands. Looks like the FOV one isn't in there yet though.

https://github.com/LostArtefacts/TRX/blob/develop/docs/tr2/COMMANDS.md

**Comment by Richard-L** [comment]
Thanks a lot, that's helpful.

**Comment by rr-** [comment]
> Here's all the commands. Looks like the FOV one isn't in there yet though.
> 
> https://github.com/LostArtefacts/TRX/blob/develop/docs/tr2/COMMANDS.md

The command for it is called `/set`, I'll add it to the documentation.

**Pull request merged**
