### PR TITLE
shell: fix skipping Eidos logo

### LINKED ISSUE #541: Improve fade skipping
Very nitpicky thing, but something you do notice after prolonged testing:

Currently the fades cannot be skipped via ESC or the action button. Take for example the initial EIDOS logo: you can only skip after fade-in, or before fade-out, but not during. It would be really nice if the skip behaviour were extended to all these three states: fade-in, image showing, fade-out.

I wonder where else this has an effect. I reckon during the end credits.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #541

### CODE REVIEW

**Review by walkawayy — APPROVED** [review]
Wouldn't this allow better skipping of other pictures too? Such as credits and maybe loading screens in the future?

**Comment by rr-** [comment]
Correct

**Comment by walkawayy** [comment]
> Correct

So maybe the changelog should reflect that? Either way, I tested and it works great.

**Comment by rr-** [comment]
Expanded the changelog to also talk about end credits. Merging

**Pull request merged**
