### PR TITLE
tr1/output: fix clipping near objects

### LINKED ISSUE #819: Rendering issue with some statics and pushable blocks
Hello, I've noticed a few rendering issues in Tomb1Main (& TombATI) that isn't present in the dos version.  I don't have the technical knowledge to explain this bug in more detail but I thought it might be helpful to create an issue for it.

**Left: DOS | Right: T1M**

GYM - Room 7

LEVEL8B - Room 16

LEVEL10A - Room 64

LEVEL10C - Room 18

### LINKED ISSUE #2003: Wrong depth buffer clipping
20241211_194553_City_of_Vilcabamba

Certain objects, when viewed from the right angle, get weirdly clipped.
Present since very old versions. @aredfan it'd be nice if we could get a confirmation if TombATI does this too.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #2003.
Above: develop
Below: this PR
The disappearing doors issue is #2005.

[output2.webm](https://github.com/user-attachments/assets/c7efc9eb-2c12-465f-9f58-c3a3cd8c335f)

### CODE REVIEW

**Comment by aredfan** [comment]
LGTM.  This PR also fixes all the issues reported in #819 as well. 👍 

There's a new issue with the Obelisk keys being partially buried in the drawbridges.

**Edit:** The sprites are also partially buried in the DOS version - which doesn't suffer from the clipping issue. It's an OG bug. 

**Sprite pickups**

Dev snapshot
1 1 Dev
PR build
1 2 PR

**3D pickups**

Dev snapshot
2 1 PR
PR build
2 2 PR

**Comment by rr-** [comment]
@aredfan I've fixed an issue with the shadows reported on Discord. Let's tackle the Obelisk pickup positions separately.

**Comment by aredfan** [comment]
Only found one new issue - Lara's shadow doesn't draw on drawbridges.

PR build
20241211_215558_Obelisk_of_Khamoon

Latest dev
20241211_215715_Obelisk_of_Khamoon

**Comment by lahm86** [comment]
What a great improvement! 👍

There are a few z issues as below. I thought initially that the air and health bars were not showing at all, but you can see them when there is no geometry/texturing like against the sky in Valley.

image
image
image

image

**Comment by rr-** [comment]
@lahm86 fixed.

@aredfan The drawbridge in Obelisk is the only trapdoor/drawbridge in the game that has this issue.
I think it's because it has its origin point placed off-center – because Lara is forced to be placed on a multiple of click height due to the drawbridge floor function, the ever so slightly raised object is bound to occlude her shadow. Because of this let's tackle this problem in #2006 as it'll require injections anyway.
out

**Review by aredfan — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]

**Comment by Richard-L** [comment]
Wow a good improvement!

@rr- just curious why the door in your comparison clip will eventually disappear still? Shouldn't it keep showing?

**Comment by aredfan** [comment]
@Richard-L The disappearing objects issue is currently captured in #2005, thus not fixed yet.

**Pull request merged**
