### PR TITLE
tr2: port Object_SetupGeneralObjects

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Required for implementing #1634.
Requires rough testing of a great deal of objects, especially by creating a save in each level with the vanilla game, and loading that save with this PR version. If there's a problem, the game should immediately crash upon loading the save. Since these are just setup routines that we decompile here, we don't need to spend too much time on regression testing for each item.

- Boat
- Fast skidoo
- Ice Palace Bells
- Big bowl
- Detonator
- Flares
- Lift / elevator
- Alarms
- Bird tweeters
- Cutscenes
- Clock chimes
- Door bell
- Earthquakes
- Final cutscene
- Gong
- Lava
- Projectiles: knifes, harpoons, flames
- Dragon explosion
- Effects: blood, body parts, bubbles ,explosions, gun flashes, flares, dragon effects, ricochets, snow and water wakes, waterfalls, splashes
- Bridges
- Drawbridges
- Windows
- Doors
- Trapdoors
- Keys and keyholes
- Puzzle items and puzzle item holes
- Switches (all kinds of)
- Pickups (all kinds of)
- Secrets

### CODE REVIEW

**Comment by lahm86** [comment]
Enemies don't carry and drop items (items remain in default position). I can't figure out why because this seems like it shouldn't be affected by the PR changes.

image

Still checking the other objects.
Edit: this is the only issue I've come across.

**Comment by aredfan** [comment]
- [x] I've noticed a brief flicker when sprites appear on the HUD after Lara picks up an item, although it's very subtle and doesn't always happen. Try picking up the jade dragon in the attached save: [savegame.zip](https://github.com/user-attachments/files/17634394/savegame.zip) This issue isn't present in 0.5 or dev snapshot (with 3d pickups disabled).

**Comment by rr-** [comment]
@aredfan @lahm86 I found a very nuanced and subtle, but remarkably substantial regression. I've put in a temporary workaround, with a proper fix on hold until we decompile the missing pieces. Let me know if it's improved now!

**Review by lahm86 — APPROVED** [review]

**Comment by rr-** [comment]
(rebased to include the 3d pickups changes)

**Review by aredfan — APPROVED** [review]
Rebasing this PR seems to have sorted out the pickup sprite flickering.

Everything else LGTM. 👍

**Pull request merged**
