### PR TITLE
fix: wrong include path

### PR DESCRIPTION
**Pull request by vvs-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Trivial one-liner fixing include path. Otherwise it doesn't compile for me.

### CODE REVIEW

**Comment by vvs-** [comment]
And why on Earth that linter changed unrelated line there and failed?

**Comment by rr-** [comment]
Thanks. While I agree that this linter has many shortcomings, it still brings enough value to the project to keep it. As far as I know, there are currently no superior alternatives available for C. At least the suggested modification it proposes is relatively minor.

**Comment by vvs-** [comment]
> While I agree that this linter has many shortcomings, it still brings enough value to the project to keep it. As far as I know, there are currently no superior alternatives available for C. At least the suggested modification it proposes is relatively minor.

I'm sorry, With all respect, I'd argue that asking random contributors to fix long standing issues using their own unrelated changes just as an excuse is not a good idea. Running linter separately from all other activity, for example, might be better.

That said, I've managed to fix that warning which I have no idea why it even happened in the first place. But other people might not be so lucky.

**Comment by rr-** [comment]
If the linters are isolated and not integrated into our regular development workflow, they may be overlooked or forgotten, defeating their purpose of catching issues early on.

I perceive your behavior to be somewhat rude – I am not requesting anything from you; it is my choice to dedicate my personal time away from my family to address this pull request and enable you to compile in a way that is not officially supported. Additionally, you indicated that you have read the contributor guidelines, but you have disregarded our recommended commit message format. From now on please be more mindful of the way you frame your messages. Thanks.

**Pull request merged**
