### PR TITLE
Introduce phasers to TR2 (part 2) + demo stuff

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

- TR2: demos converted to a phase
- TR1 and TR2: demos can now be only interrupted with an action or an escape keys (this is to let the user play with the render settings, turbo speed etc. as they play)
- TR1 and TR2: add an ability to play specific demo by adding an optional demo number argument to the `/demo` command

### CODE REVIEW

**Comment by rr-** [comment]
Found a bug with loading saves, will fix shortly.

**Comment by aredfan** [comment]
I found just one issue.

- [x] If you wait for the demo mode to start, only the first demo will be shown for both TR1X and TR2X.

**Comment by rr-** [comment]
> I found just one issue.
> 
> * [ ]  If you wait for the demo mode to start, only the first demo will be shown for both TR1X and TR2X.

Thanks @aredfan – addressed.

**Review by aredfan — APPROVED** [review]
LGTM 👍

**Review by lahm86 — APPROVED** [review]

**Pull request merged**
