### PR TITLE
phase: fix Lara twitching before pause

### LINKED ISSUE #1258: Lara twitches for a single frame with negative turbo speed in 60 FPS
When hitting pause, entering inventory etc.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, r it is an internal change

#### Description

Fixes #1258
I made sure not to break the recently fixed fade out skips, as these could be affected by the changes in this PR.

### CODE REVIEW

**Review by walkawayy — APPROVED** [review]
LGTM.

**Comment by aredfan** [comment]
@rr- Is there a dev build to test?

**Comment by rr-** [comment]
@aredfan https://nebula.wind.garden/serve/pub/TR1X%203.1.1-127-g1ce6f00-Windows.zip

**Comment by aredfan** [comment]
There's no sign of twitching with negative turbo. 👍 

I also checked all cases of fade skips.  LGTM.

**Review by aredfan — APPROVED** [review]

**Pull request merged**
