### PR TITLE
TR2: Add turbo cheat

### LINKED ISSUE #1639: Add Turbo mode
Done at hand of the `TAB` key in TR1X. Very convenient for block pushing or long ladder climbing in TR2 during testing.

I would toggle double the game speed. Walkaway had added two different speeds to step through at hand of the TAB key. Personally I find this a little unintuitive to use.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1639. It's somewhat of a spontaneous update. I needed to move the clock to libtrx for the 3D pickups ticket, and since adding the turbo cheat seemed like a low hanging fruit at this point, I decided to give it a go and it seems to be working fine.

This needs some regression testing, specifically:

- **TR1**: Test configuration - loading and saving through keyboard cycling, using `/set`, and using `/speed`.
- **TR2**: Thoroughly test clock behavior with pictures, FMVs, demos, and movies. While I noticed that FMVs currently are unable to speed up, I suggest we address this in a separate ticket.

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
The only minor issue/difference I've noticed is the demo wait time. In TR1X, with speed set to 2, the wait time is ~4 seconds. In TR2X it remains ~30 seconds regardless of speed.
Otherwise, LGTM.

**Comment by aredfan** [comment]
A few things I noticed for TR2X:

- [x] The inventory clock in TR1X is unaffected by turbo speeds, whereas the TR2X clock is affected. Should TR2X match TR1X?
- [x] I don't think there's a difference between turbo speeds 0 and 1 in the case of TR2X. A good place to compare this is with the animated water textures in Temple of Xian room 89, and Lost Valley room 24.
- [x] <del>Positive turbo speeds have no effect in cutscenes.</del> **Edit:** I just re-read the OP, I'm guessing this issue is out of scope.

**Comment by rr-** [comment]
@aredfan addressed all.

**Comment by aredfan** [comment]
@rr- Thank you. 👍 

The different turbo speeds in demos, cutscenes and gameplay all LGTM. The timer is no longer affected by turbo speeds. Lahm's issue with the demo countdown is fixed as well.

| Turbo speed | -2 | -1 | 0   | 1   | 2   |
|-------------|----|----|-----|-----|-----|
| Demo wait   | 2m | 1m | 30s | 15s | 10s |

__________

I've noticed these new issues while testing the latest PR build:

- [x] The assault course timer no longer resets when Lara runs back to the start.
- [x] The start up copyright screen displays for roughly 6s in the PR build, and 3s in OG/dev snapshot.
- [x] The credit images display for roughly 15s in the PR build, and 7.5s in OG/dev snapshot.

| Turbo speed  | -2 | -1  | 0   | 1    | 2  |
|--------------|----|-----|-----|------|----|
| Credit image | 1m | 30s | 15s | 7.5s | 5s |

**Comment by rr-** [comment]
> @rr- Thank you. 👍
> 
> The different turbo speeds in demos, cutscenes and gameplay all LGTM. The timer is no longer affected by turbo speeds. Lahm's issue with the demo countdown is fixed as well.
> 
> Turbo speed	-2	-1	0	1	2
> Demo wait	2m	1m	30s	15s	10s
> I've noticed these new issues while testing the latest PR build:
> 
> * [ ]  The assault course timer no longer resets when Lara runs back to the start.
> * [ ]  The start up copyright screen displays for roughly 6s in the PR build, and 3s in OG/dev snapshot.
> * [ ]  The credit images display for roughly 15s in the PR build, and 7.5s in OG/dev snapshot.
> 
> Turbo speed	-2	-1	0	1	2
> Credit image	1m	30s	15s	7.5s	5s

Thanks – fixed all.
I didn't know the stopwatch in the gym is tied directly to the assault course.

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
> Thanks – fixed all.
> I didn't know the stopwatch in the gym is tied directly to the assault course.

Confirmed - all prior issues are fixed, thank you.

| Turbo speed  | -2  | -1  | 0    | 1     | 2   |
|--------------|-----|-----|------|-------|-----|
| Credit image | 30s | 15s | 7.5s | 3.75s | 2.5 |

**Pull request merged**
