### PR TITLE
bear: fix the bear pat attack so it does not miss Lara

### LINKED ISSUE #450: Bug: issues with BEAR_ATTACK1 and BEAR_ATTACK2
From now on, I will refer to BEAR_ATTACK1 as "bite" and BEAR_ATTACK2 as "pat". The bear also deals charging damage whenever it's running and touches Lara, similarly to the T-Rex and Torso.

### 1st issue: the bear stops biting.
Sometimes the bear doesn't bite anymore, but only charges against Lara. I think this is unintentional, especially since the bear never stops dealing charge damage even when it's actively biting Lara. It also makes the bear an easy fight since charging barely deals any damage compared to biting. See the 3 videos below:

Bear acting as it should: biting Lara every time it gets close to her.

https://user-images.githubusercontent.com/97730054/155711694-5d03edcb-4754-4cb3-b693-9ebecfe10576.mp4

Bear only charging. **I think this should be fixed so that the bear behaves as above.**

https://user-images.githubusercontent.com/97730054/155711769-fd8a951b-d26d-42bf-a1e6-83d435a11926.mp4

Here you can see that when the bear is actively biting, it also deals charge damage whenever it touches Lara between the bites. This indicates that the charge damage is just an additional feature and not a deliberate "charge only mode" that the bear enters.

https://user-images.githubusercontent.com/97730054/155711975-ac40d601-09ae-4c75-8c98-32f285472cfa.mp4

Also, my tests indicate that if the bear is behaving correctly, it can sometimes be "broken" by going out of reach and then back. Same applies vice versa: a broken bear can sometimes be fixed by going out of its reach. Usually the bear stands up on its rear legs when this happens.

** **

### 2nd issue: bear's pat attack is not useful.
That might sound arbitrary or something that should not be touched but hear me out. It's a compilation of problems with the pat attack and I'm not sure what exactly is causing it. But I think it's a beautiful move and with some slight changes it could work so much better that it's worth fixing. The problems might stem from a similar "stuck in a no-attack mode" than issue 1, the range of the attack, the hitbox of the attack, or any compilation of these.

First problem is that the bear simply doesn't use the pat even though it looks like it could and should. Here the bear is simply walking towards Lara, not doing anything threatening. No matter whether I stay close to the bear or go further, it doesn't attack.

https://user-images.githubusercontent.com/97730054/155714094-73ac0746-e391-43c2-952d-f9b413deabaf.mp4

Second problem is that the hitbox of the pat doesn't seem very accurate. In these 2 videos I'm standing right next to the bear and you can even see Lara get "hit" by the bear but still no damage.

https://user-images.githubusercontent.com/97730054/155714700-0d8b1799-f7df-445f-9109-6c0baccf0218.mp4

https://user-images.githubusercontent.com/97730054/155714711-c47243a1-c2aa-47e9-b31e-d39c30611854.mp4

Third problem is what  you see in the beginning of the previous video (pat_no_damage2). The range of the attack is so big that the bear is usually way too far from Lara for the pat to hit her. Here is another video of this issue:

https://user-images.githubusercontent.com/97730054/155715909-e7b08b59-9e00-41f9-88d0-5b17ed882974.mp4

The pat has a range of 2 blocks. Here it thinks it should pat Lara, even though its attack will never hit her. If I take a step back, it will stop and start walking towards Lara, never attacking her again. If I get closer, the same happens: just when I'm about to enter the actual hitbox range, the bear stops attacking. And it never tries to pat again, not even when I try to regain the ~2 block distance.

[save_tr1_04.zip](https://github.com/rr-/Tomb1Main/files/8141156/save_tr1_04.zip)

Here is a save file where the bear has just stood up behind Lara, and will start its infinite patting if you don't move.

**I think this should be fixed so that the bear actually uses pat when it's close to Lara, and that the pat hitbox is good enough to hit Lara when the bear does attack.**

### PR DESCRIPTION
**Pull request by walkawayy**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed the bear pat attack so it does not miss Lara. Fix done by ChocolateFan.
Does not solve all the things listed in the original issue because they were user preferred behavior changes and not really bug fixes. Requesting translations.

### CODE REVIEW

**Comment by walkawayy** [comment]
@ajtudela another translation request please:
`Fixes bear pat attack so it does not miss Lara.`

**Review by rr- — APPROVED** [review]

**Comment by ajtudela** [comment]
> @ajtudela another translation request please:

Could you explain me this fix so I can make a better translation?

**Comment by walkawayy** [comment]
> > @ajtudela another translation request please:
> 
> Could you explain me this fix so I can make a better translation?

It fixes when the bear is on its hind legs and "pats" Lara. The range is bugged so it does not damage. That's the name for the attack in the code. Here's the relevant video from the issue:

https://github.com/LostArtefacts/Tomb1Main/assets/81546780/00a3ccb0-9a92-4969-aabb-b6eb8befb80a

Here's a random gif of a dog "patting" another dog.

https://64.media.tumblr.com/10591d32af065d3b671836043b7a6f01/tumblr_p8dbscYrKt1vb46leo1_400.gif

**Comment by rr-** [comment]
>https://64.media.tumblr.com/10591d32af065d3b671836043b7a6f01/tumblr_p8dbscYrKt1vb46leo1_400.gif

We need to get this implemented ASAP

**Comment by ajtudela** [comment]
Nice gif, hahaha

The translation would be:
```
Corrige el ataque del oso para que golpee a Lara.
```

**Pull request merged**
