### PR TITLE
shell: fix a game crash if the action button is held down

### LINKED ISSUE #646: Holding down select during game exit crashes the game
Holding the `select` key during `Shell_Shutdown` spins a call to `Input_Update()` in a while loop. I tested holding it after selecting exit game from the passport, and the game got stuck in a black screen and had a Windows crash error. Is there a reason the game does this at all and doesn't just do a shutdown? I checked and this seems like an OG bug (at least a TombATI bug).

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #646.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed a game crash on shutdown if the action button is held down.
...

### CODE REVIEW

**Review by rr- — APPROVED** [review]

**Review by rr- — COMMENTED** [review]
Would be good to mention the version that broke this.

**Comment by walkawayy** [comment]
It's an OG bug. The same problem exists in TombATI.

https://github.com/rr-/Tomb1Main/commit/44edb5a51020da23a85564cd6d03227b285d9aa9

**Comment by rr-** [comment]
I know the code is there looking similar, but I'm pretty sure it used not to freeze the game.

**Comment by walkawayy** [comment]
I'll test again later tonight to confirm, but I did test TombATI when I opened the issue. I held down `Control` as I exited the game and it spikes your CPU usage and the game crashes. I also couldn't find `WinVidSpinMessageLoop` when searching Github since it seems that function is gone, so I didn't look into what that was doing.

**Comment by walkawayy** [comment]
Finally tracked it down... this is what `WinSpinMessageLoop` was originally doing from https://github.com/rr-/Tomb1Main/commit/5849a1ba46287762f2197360481ac12e2f57cb34. I have no idea what the code is doing however.
```
int32_t WinSpinMessageLoop()
{
    MSG msg;
    while (PeekMessageA(&msg, 0, 0, 0, PM_NOREMOVE)) {
        if (!GetMessageA(&msg, 0, 0, 0)) {
            TerminateGame(0);
        }

        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }

    int32_t time_ms = timeGetTime();
    int32_t old_ticks = Ticks;
    Ticks = time_ms * 2 * 30 / 1000;
    return Ticks - old_ticks;
}
```

**Pull request merged**
