### PR TITLE
option: fix the compass and new game menus at high text scaling

### LINKED ISSUE #648: Compass screen broken at 2x text scaling
image

The New Game menu also isn't centered at high scaling:
20221117_184824_Title

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #648.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed the compass and new game menus at high text scaling.
...

### CODE REVIEW

**Comment by walkawayy** [comment]
Compass at high scaling:
20221120_113638_Caves


New game at high scaling:
20221120_164936_Title

**Review by rr- — COMMENTED** [review]
How does it look at higher resolutions, and how do select level / init save requesters look?

**Comment by walkawayy** [comment]
1440p .5x text scaling is actually messed up too, so I'll fix that. This was not caused by this branch and is actually in the current develop branch:

image

**Comment by walkawayy** [comment]
Here's a 480p album with .5, 1.0, 1.5, and 2.0 scaling:
https://imgur.com/a/8vC5EqD

Here's a 1440p album with .5, 1.0, 1.5, and 2.0 scaling:
https://imgur.com/a/K469XEV

**Comment by rr-** [comment]
Is it possible to move the NG dialog a bit closer to the passport's center?

**Comment by walkawayy** [comment]
How about this?

https://imgur.com/a/Fmn1T0o

**Review by rr- — APPROVED** [review]
Please leave a comment in the code about the reason for this fancy formula.

Otherwise LGTM, but I'm missing the screenshots for Select Level and Save requesters that appear in the files changed. If they're centered in similar manner, it can be merged.

**Comment by walkawayy** [comment]
> Here's a 480p album with .5, 1.0, 1.5, and 2.0 scaling: https://imgur.com/a/8vC5EqD
> 
> Here's a 1440p album with .5, 1.0, 1.5, and 2.0 scaling: https://imgur.com/a/K469XEV

Save requestor pics are included with the (now outdated) new game pics from the albums I posted earlier.
I didn't post select level pics since it's the same position as the save requestor.

I did now notice something though. The in game inventory passport is drawn at a different height than the menu one. Oof. This means the save requestor at the same position looks off in game. Not sure how best to handle the position since it will vary between menu vs game mode without some weird hard coded checks. Any ideas?

20221129_173502_Title

20221129_173453_Caves

**Comment by rr-** [comment]
Oh dear… No, I don't have suggestions. IMO it's OK to hardcode a check for the presence of the menu, but we'll need a comment explaining what is happening.

**Comment by walkawayy** [comment]
Alright hopefully this is the last iteration needed. I compared the title vs in game requestors in Lara's Home since I had to adjust the new game position there. I'm linking albums comparing position at .5 and 2.0 text scaling at 1440p. But I tested at 1.0 and 1.5 text scaling at 480p also. Everything looks good to me.

New game requestor:
https://imgur.com/a/hj7oF7O

Save requestor (select level requestor is at same position):
https://imgur.com/a/kWVS1lN


And FYI the reason they are at different positions is because of this code in `Inv_Ring_Init`:
```
    if (g_InvMode == INV_TITLE_MODE) {
        ring->camera_pitch = 1024;
    } else {
        ring->camera_pitch = 0;
    }
```

**Comment by walkawayy** [comment]
When I run `make imports` on my local code, I get no changes. I'm not sure why Github's import checker is mad about `option_control.c`. I didn't touch that file in this PR.

**Comment by rr-** [comment]
The linters complain

**Comment by walkawayy** [comment]
> The linters complain

Ya see my post above. I'm not sure why.

**Comment by rr-** [comment]
Sorry I missed it. I agree it's weird, but let's nonetheless add these imports and move on. IWYU can be creepy sometimes.

**Comment by walkawayy** [comment]
Good to merge?

**Comment by rr-** [comment]
Yes I have already approved it before :)

**Pull request merged**
