### PR TITLE
Migrate from wgl_ext to SDL_GL

### PR DESCRIPTION
**Pull request by carlo-bramini**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

For improving the porting, it would be worth to migrate to SDL_GL functions made available into SDL2. They provide the same functionalities of wgl_ext without the need of platform-specific calls to functions that will work only on Windows. After these changes, `wgl_ext.c` and `wgl_ext.h` are not used anymore and they can be safely deleted.

The source `src\gfx\gl\gl_core_3_3.c` could be also simplified by using `SDL_GL_GetProcAddress()`, but at the moment the code does not make direct use of platform-specific functions, so I left that file as it is.

### CODE REVIEW

**Review by rr- — APPROVED** [review]
I'm not yet merging as it'd need more testing.

**Comment by rr-** [comment]
BTW after this, is it OK for us to remove the Windows dependency altogether?

**Comment by carlo-bramini** [comment]
> BTW after this, is it OK for us to remove the Windows dependency altogether?

This is Tomb1Main running on Linux Debian 12, AMD64 distro.
I switched from fullscreen to windowed mode, just for showing the desktop of the window manager.
It is running the demo version for PC by using the hack that I described in issue #667.
It is using this patch and also the one provided by #673, which still needs to satisfy the linters.

Tomb Raider Demo PC on Debian 12

Actually, there is one more thing that should be remembered when running this game (demo or full version) on Linux or others:

**Filesystem can be case sensitive for file names.**

At the beginning, I was going crazy for some minutes because the engine was not able to find any file.
Later, I found the trick: the .json5 files use file names written in lower case, for example "data\\level2.phd", but the true file name was "data/LEVEL2.PHD" or "DATA/LEVEL2.PHD" (it depends if you copy all the files into data/ or you copy "DATA/" directory with all files inside).
So, for running the demo PC level on any UNIX-like and Windows systems, I also fixed my .json5 file by replacing '\\' with '/' as directory separator and I converted the file names to capital letters.

Besides this little troubles, these first results are amazing.

**Comment by rr-** [comment]
@walkawayy could you take a look if this breaks anything on Windows, especially around handling fullscreen / windowed?

**Comment by carlo-bramini** [comment]
I tested the engine on a gaming notebook Acer Nitro 5 with an NVIDIA GTX 1650 Ti and I got an ugly graphic result, see attached screenshot. This happens because it is needed to set also the minimum properties of the SDL GL context before calling SDL_CreateWindow(). After the fix, the graphic output is correct also on this device.

Senza titolo

**Comment by walkawayy** [comment]
I get errors and warnings when trying to build (Windows 11):
```
[181/187] Compiling C object Tomb1Main.exe.p/src_gfx_context.c.obj
In file included from ../src/gfx/gl/buffer.h:3,
                 from ../src/gfx/2d/2d_renderer.h:3,
                 from ../src/gfx/context.h:3,
                 from ../src/gfx/context.c:1:
../src/gfx/context.c: In function ‘get_extension_supported’:
../src/gfx/gl/gl_core_3_3.h:3025:22: warning: pointer targets in initialization of ‘const char *’ from ‘const GLubyte *’ {aka ‘const unsigned char *’} differ in signedness [-Wpointer-sign]
 3025 | #define glGetStringi _ptrc_glGetStringi
      |                      ^~~~~~~~~~~~~~~~~~
../src/gfx/context.c:40:30: note: in expansion of macro ‘glGetStringi’
   40 |         const char *gl_ext = glGetStringi(GL_EXTENSIONS, i);
      |                              ^~~~~~~~~~~~
../src/gfx/context.c: In function ‘GFX_Context_Attach’:
../src/gfx/context.c:77:9: warning: implicit declaration of function ‘GFX_GL_CheckError’ [-Wimplicit-function-declaration]
   77 |         GFX_GL_CheckError();
      |         ^~~~~~~~~~~~~~~~~
[182/187] Compiling C object Tomb1Main.exe.p/src_gfx_gl_gl_core_3_3.c.obj
[183/187] Compiling C object Tomb1Main.exe.p/src_specific_s_audio_sample.c.obj
[184/187] Compiling C object Tomb1Main.exe.p/src_specific_s_input.c.obj
[185/187] Compiling C object Tomb1Main.exe.p/src_specific_s_fmv.c.obj
[186/187] Compiling C object Tomb1Main.exe.p/src_specific_s_shell.c.obj
[187/187] Linking target Tomb1Main.exe
FAILED: Tomb1Main.exe 
...
/usr/bin/i686-w64-mingw32-ld: Tomb1Main.exe.p/src_gfx_context.c.obj: in function `GFX_Context_Attach':
/app/build/../src/gfx/context.c:77: undefined reference to `GFX_GL_CheckError'
```

**Comment by walkawayy** [comment]
One more warning:
```
[178/187] Compiling C object Tomb1Main.exe.p/src_gfx_context.c.obj
In file included from ../src/gfx/gl/buffer.h:3,
                 from ../src/gfx/2d/2d_renderer.h:3,
                 from ../src/gfx/context.h:3,
                 from ../src/gfx/context.c:1:
../src/gfx/context.c: In function ‘get_extension_supported’:
../src/gfx/gl/gl_core_3_3.h:3025:22: warning: pointer targets in initialization of ‘const char *’ from ‘const GLubyte *’ {aka ‘const unsigned char *’} differ in signedness [-Wpointer-sign]
 3025 | #define glGetStringi _ptrc_glGetStringi
      |                      ^~~~~~~~~~~~~~~~~~
../src/gfx/context.c:41:30: note: in expansion of macro ‘glGetStringi’
   41 |         const char *gl_ext = glGetStringi(GL_EXTENSIONS, i);
      |                              ^~~~~~~~~~~~
```

**Comment by walkawayy** [comment]
Ah I see you force pushed a change to address the warning. I'll try the new build today.

**Review by walkawayy — APPROVED** [review]
LGTM with the latest changes. I tested different resolutions, I was able to alt+enter to toggle windowed, mode, and FMVS / cutscenes worked fine. I'll let rr double check.

**Pull request merged**
