### PR TITLE
build: build every pull request

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This will simplify the testing process for @LostArtefacts/qa. After merging this PR, each new pull request will include four additional checks: builds for Linux, Windows, Windows installer, and macOS. These are release builds and do not include debug symbols. Although accessing the builds is somewhat complicated, the benefit is that the process becomes automated and will apply to all pull requests and contributors. Here's a video showing where to find them

https://github.com/user-attachments/assets/9f710c54-b88f-4e42-be63-3d510c144552

### CODE REVIEW

**Comment by rr-** [comment]
I think the failing macOS job has to do with me pushing this pull request from my fork, and can be safely ignored.

**Comment by walkawayy** [comment]
Amazing! This will be super useful. The only issue I noticed is the Mac signing process again. :/ That thing is always causing problems.

https://github.com/LostArtefacts/TR1X/actions/runs/10636314044/job/29487839947#step:2:30

EDIT: Oh nice about the Mac issue. LGTM!

**Review by walkawayy — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
I was able to follow the steps in the video and download a build.

@rr- Thank you very much for working to make this possible, much appreciated. 👍

**Comment by rr-** [comment]
It turns out that PRs from forks in GitHub Actions won't be able to use the upstream repository secrets, as explained here: https://github.com/orgs/community/discussions/50161. While workarounds exist, they are risky. Since Mac builds are the only ones that require secrets, I think I'll just remove Mac builds from this process. This won't affect the develop snapshots and regular releases.

**Pull request merged**
