### PR TITLE
inject: fix music trigger setups in Folly

### LINKED ISSUE #865: Prevent music trigger if room is closed
This occurred to me on a recent PS1 playthrough with a family member (still the only way to get a German dub without replacing audio files), and it's the same in TR1M, and made me think if it's worth adding extra code that prevents music triggers if the intended room (or moment) are still inaccessible.

Consider this case of the Neptune room in Folly (requires audio):

https://github.com/LostArtefacts/Tomb1Main/assets/4934209/a9ad52ef-311a-4776-834d-676f6e5ab4c2

I felt it's unfortunate to "waste" the music because the music trigger should maybe have been on a tile behind the door here. The music is intended to accompany the long dive down. Instead here it plays as you continue through the main room of the folly. I suppose there might be more occurrences of this throughout the game.

I assume this would either mean to inject a changed level file where the music trigger has been moved behind the door, or add code logic that only plays music tracks _if_ a specific door has been opened. Both don't seem overly desirable maybe. Let me know your thoughts.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #865.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

We move the Neptune room trigger here behind the door, so it's on par with the Thor room.

Additionally, the track that was intended to be played after using the 4 keys at the end of the level has been restored. The original setup has the music command on the masked triggers, but that setup is not possible because of how the music is controlled (and I don't believe it's possible in any game). The standard for custom levels is to use heavy triggers for this kind of setup, so we do the same here and make use of the boulder that opens the door.

https://www.youtube.com/watch?v=jSwCXs2Eizk

### CODE REVIEW

**Review by walkawayy — APPROVED** [review]
Nice!

**Comment by Richard-L** [comment]
This is lovely Lahm, but allow two comments:
- Would it be even better to move the Neptune music trigger one further tile back into the room itself? It seems like Thor's happens only when past the door and I like it.
- I don't fully understand the need for a boulder at the end to enable the added track, but it does sound quite weird to hear one rolling somewhere in this moment. Is there no other way around this?

In any case, thank you

**Comment by rr-** [comment]
Yeah, can we do something about the boulder sound?

**Comment by lahm86** [comment]
Yes, it's no problem to shift the Neptune trigger further into the room.

Re the boulder, there are two options.

1. Disable the SFX on the object
2. Move the hidden room elsewhere on the map so you can't hear it

I think (2) is best, otherwise you wouldn't hear the boulder in the Atlas room either.  The room's position is arbitrary as it has no portals. This will need a little extra injection code, but I don't think it will be too much.

image

**Comment by rr-** [comment]
Yeah let's go with (2).

**Comment by lahm86** [comment]
Let me know what you think: https://youtu.be/ewd21yybAcU

For the additional code, we do the basic room position shift, and then move any items with the same room number to follow i.e. the boulder. If we're shifting by Y, we need to update the sectors and the vertices - although the latter isn't so important here as the room is never drawn, but it's good practice I feel (I'm not sure if we'll ever need this for anything else, but it's there if we do).

For interest, this is the room's new position.

image

**Comment by rr-** [comment]
Sounds good to be on a mobile. I'll be only able to test it on a PC tomorrow.

**Review by walkawayy — APPROVED** [review]
LGTM!

**Comment by Richard-L** [comment]
That's perfect Lahm ♥️

**Review by rr- — APPROVED** [review]

**Pull request merged**
