### PR TITLE
inject: add the ability to insert floor data

### LINKED ISSUE #751: Missing trigger tile for a rat | Tomb of Tihocan
It seems I keep raising issues for @lahm86 lately, I'm so very sorry.  Also tagging @Richard-L too in case he has any thoughts to share.

This issue is about a rat which doesn't seem to trigger until Lara gets closer.

20230309_121008_Tomb_of_Tihocan

The interesting thing is the trigger tiles are there and extends all the way to the edge, see the screenshot below.

Screenshot (227)

However when flipmap is triggered the tiles are reduced.  I suspect this is a mistake.

Screenshot (228)

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #751.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This allows us to insert new floor data values, and is used here to restore the missing rat trigger in Tomb of Tihocan room 62.

### CODE REVIEW

**Review by rr- — COMMENTED** [review]
This is only capable of overwriting existing FD, are there cases where we'll want to insert or remove data and thus realign the entire thing?

**Comment by lahm86** [comment]
> This is only capable of overwriting existing FD, are there cases where we'll want to insert or remove data and thus realign the entire thing?

This appends on to the end of the array - the tile in Tihocan as it stands has no floor data. A previous injection update did some forward planning here - we aggregate how much extra FD space is needed for all injections, then it's allocated in `level.c`.

https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/inject.c#L293
https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/level.c#L236

The only other case that's been identified will be for moving the music trigger behind the Neptune door in Folly (#865). My plan for here was to change the existing trigger in front of the door to play track `MX_UNUSED_0` (i.e. so it will effectively be skipped in `music.c`) and then create a new entry for the trigger behind the door with the correct track plus the flip command that's there already. This would leave the old values in the array, they would just be unreferenced.

The other remaining cases are for #942, but these are just type changes, so direct `int16_t` replacements.

I can imagine another large repeated FD loop to achieve removal/realignment. The injections would also need to aggregate removal size so that the FD array is set initially to the correct size in `level.c` (I don't believe `GameBuf` can realloc/free individual buffers?) and from that it could get tricky in terms of implementation order of the injections themselves. For just the Folly case, I don't feel it's worth it - what do you think?

If we manage to get somewhere with #941, this will become even tidier. So the level would load the FD array, we would inject/modify as required, and then it would be parsed into the structures. Data that's no longer pointed to would be discarded.

**Comment by rr-** [comment]
Thanks for clarification.

>I don't believe GameBuf can realloc/free individual buffers?

I think so too.

> For just the Folly case, I don't feel it's worth it - what do you think?

Agreed.

> My plan for here was to change the existing trigger in front of the door to play track `MX_UNUSED_0`

What if we go even further and introduce a new trigger type that does nothing? This way we can nullify more. Perhaps we don't even need to introduce anything and just overwrite the bytes with any value that's currently unhandled (I suggest using all bits set to 1).

**Review by rr- — APPROVED** [review]

**Comment by lahm86** [comment]
> What if we go even further and introduce a new trigger type that does nothing? 

Oh that's a great point - we could use the existing `TT_DUMMY` for that scenario. This is skipped in `Room_TestTriggers` as-is.

**Review by walkawayy — APPROVED** [review]

**Pull request merged**
