### PR TITLE
output: fix initial flicker

### LINKED ISSUE #1322: Title screen flashes briefly at a wrong viewport size during game launch
The game is rendered at what seems to be the initial window size, rather than desktop size.

For the FBO render mode, this lasts 1 frame.
For the window size render mode, this lasts 2 frames.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Addresses #1322 – decreases the flicker down to what feels like a single frame. This is the best I can do at the moment.

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
Looks good, but this happens if you launch maximized or in full screen mode:

image

**Review by walkawayy — APPROVED** [review]
Seems much better to me. I don't get flickering on W11 as far as I can tell.

**Comment by rr-** [comment]
> Looks good, but this happens if you launch maximized or in full screen mode:
> 
> image

I can't reproduce on Windows (through Wine + virtual desktop) or Linux, on 640x480 or desktop resolution.

**Comment by lahm86** [comment]
> > Looks good, but this happens if you launch maximized or in full screen mode:
> > image
> 
> I can't reproduce on Windows (through Wine + virtual desktop) or Linux, on 640x480 or desktop resolution.

The only way I can solve it is by undoing the changes, but I feel I'm missing something.

Here is a demo of it. So full-screen and maximized window mode result in the small display. Even if you reset the window, when you launch a level it goes back to a small output.

https://youtu.be/m8MEXSSNzFE

I've also noticed it doesn't remember my window size - so resizing a window, closing and reopening, the original size is restored.

@walkawayy assuming it was all good on your system?

**Comment by rr-** [comment]
I've reworked the fix – can you please retest?

**Review by lahm86 — APPROVED** [review]
Works perfectly, thanks 😄

**Pull request merged**
