### PR TITLE
tr2/decomp: fix windowed screenshots not working

### LINKED ISSUE #1766: OG bug: screenshots do not work in windowed mode

### LINKED ISSUE #1773: TR2X: improve screenshot support
Currently 8-bit screenshots get saved as .pcx, 16-bit screenshots get saved as .tga, while 24-bit and 32-bit screenshots simply do not work at all (#1766). TR1X has the option to choose either jpg or png as the format, puts the screenshots in their own directory, and has a naming conflict resolver. We should implement all of that in TR2 as well.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1766.

### CODE REVIEW

**Comment by rr-** [comment]
This is mostly for testing, as screenshots in general will need a rewrite anyway.

**Comment by walkawayy** [comment]
I get a black screen still even in fullscreen. But screenshots / screen recording has never worked for me while I'm stuck running in SW mode.

image

**Comment by aredfan** [comment]
- [x] In full screen, the `s` key takes several screenshots at once but these screenshots are good. It may be that the input isn't debouncing.
- [x] In windowed mode, the `s` key causes the game to crash but it does produce just one screenshot which is all pink.

**My setup:**
Screenshot

**Comment by rr-** [comment]
@aredfan updated.
- Fixed debouncing the "S" key
- Fixed (hopefully) the pink tint and crash in the windowed mode
- Changed the screenshots to be placed in `/screenshots` directory
- Changed the screenshot names to include the current date, time and the level title; adding numeric suffixes in case there are conflicts (like in TR1X)
- Changed the default screenshot format to be JPG (like in TR1X)
- Added a configuration switch in the config tool to let the player use PNG instead

Since some parts were taken from TR1X and the code for both games was de-duplicated via libtrx, it makes sense to test TR1 as well.

**Comment by aredfan** [comment]
@rr- The `s` key debouncing and the crash issues are both fixed, thank you. The screenshot directory and names are working as expected too.

I came across these issues when testing the TR2X build.

- [x] The screenshots retain a pink tint when using windowed mode.
- [x] Switching to PNG format in config has no effect, the game continue to produce screenshots in JPEG format.
- [x] When I quit the game I get an error message, captured below.

Screenshot

**Comment by rr-** [comment]
@aredfan  the pink tint issue should be hopefully gone now. If you're still experiencing it, could you please share the relevant logs that resemble this format?

```
game/output.c 4527 Output_MakeScreenshot bit_count = 32
game/output.c 4528 Output_MakeScreenshot r mask = 00ff0000
game/output.c 4529 Output_MakeScreenshot g mask = 0000ff00
game/output.c 4530 Output_MakeScreenshot b mask = 000000ff
```

I've also fixed the stealthy bug with the settings. It was really nasty and could've unpredictably impacted wildly different parts of the game code, so I'm glad we identified it this early.

While I couldn't replicate the failed assertion, I made some tweaks that might help. Please let me know if you're still experiencing the problem. Thanks!

**Comment by aredfan** [comment]
@rr- It's great news you were able to fix the stealthy bug early on, well done.  I can also confirm that TR2X is now able to create PNG screenshots.

In windowed mode, the screenshots remain pink regardless of the selected screenshot format. Here's my log file: [TR2X.log](https://github.com/user-attachments/files/17556410/TR2X.log)

I do still get the same failed assertion when quitting the game whether that's via the passport or `/exit`. I also made sure to check the latest dev snapshot and the issue is currently confined to this PR.

LMK if you need anything else.

**Comment by rr-** [comment]
> @rr- It's great news you were able to fix the stealthy bug early on, well done. I can also confirm that TR2X is now able to create PNG screenshots.
> 
> In windowed mode, the screenshots remain pink regardless of the selected screenshot format. Here's my log file: [TR2X.log](https://github.com/user-attachments/files/17556410/TR2X.log)
> 
> I do still get the same failed assertion when quitting the game whether that's via the passport or `/exit`. I also made sure to check the latest dev snapshot and the issue is currently confined to this PR.
> 
> LMK if you need anything else.

I've identified the issue with the shutdown, and it should be now fixed.

Re: pink tint – looks like our machines report to be using identical pixel formats, but for some reason, my GPU uses RGB while yours actually uses BGR. I've changed the way we retrieve the pixel format to match what we use in FMVs. LMK if it's any better.

**Comment by aredfan** [comment]
@rr- The assertion failed message is gone now, thank you. 🎉 

The game still produces pink tinted screenshots when in windowed mode. I made sure to have the FMV folder present in the game directory when testing the current PR build.

**Comment by rr-** [comment]
@aredfan can you please try the most recent build?

**Review by aredfan — APPROVED** [review]
@rr- Yes of course. The TR2X screenshots are now fixed in windowed mode, thank you.

I also tested TR1X and the screenshots are working as expected. LGTM.

**Review by lahm86 — APPROVED** [review]

**Review by walkawayy — APPROVED** [review]
Everything works fine for me in fullscreen. I can't test windowed mode with the SW renderer.

**Pull request merged**
