### PR TITLE
Convert inventory to a phase

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This concludes refactoring out nested loops. The only usage left is `#define FRAME_BUFFER` which I haven't tested(!).

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
Save crystals seem to respawn - so if you use one, then reload, the crystal reappears and you can use it again.

Everything else looks good inventory-wise from what I can tell. 

Also re buffering, inventory buffering now advances 1 frame rather than 2, but I don't think this is an issue. It just means that any setups using it would be twice as long; F-key buffering still works fine, so that would arguably make setups quicker anyway as you needn't wait for the inventory animation. As TR1X isn't a speedrunning tool, I think overall it's fine for the "casual setup" player.

Here the first setup is what's done normally to get Lara into the right position. The second setup shows it needs double buffers. The Khamoon setup works fine using F-key buffering.
https://youtu.be/9rwbUmI7W-Y

**Comment by rr-** [comment]
Thanks @lahm86 this should be now fixed.

**Review by lahm86 — APPROVED** [review]
Looks good!

**Review by walkawayy — APPROVED** [review]
I didn't notice any issues while testing!

**Pull request merged**
