### PR TITLE
lara_look: add inverted look option

### LINKED ISSUE #700: Add an inverted look option
Unlike the camera rotation which can be customized, pressing down while holding the Look button will move the camera down and pressing up will make it move up and it can't be changed (I for example like it inverted).
While you're at it, a camera rotation speed slider would be nice, I find the default speed very slow.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #700.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Adds a camera option to the controls menu. Adds an inverted look option to that new menu.
...

### CODE REVIEW

**Review by rr- — COMMENTED** [review]
The refactor to `Lara_LookLeftRight` doesn't seem backwards compatible - I think Lara will now turn her head twice as slow when in surf state. Either way let's have this refactor done as a separate pull request.

**Comment by walkawayy** [comment]
@ajtudela would you be able to provide a Spanish translation for this config option?

```
"Title": "Enable inverted look",
"Description": "Inverts the Y axis controls when Lara looks."
```

**Comment by ajtudela** [comment]
Sure!
```
"Title": "Habilitar la vista invertida",
"Description": "Invierte los controles del eje Y cuando Lara mira."
```

**Comment by walkawayy** [comment]
Ok I reworked this PR into a config tool option.

EDIT: Oops I was building the installer not the config tool. I don't know how to build the config tool though.

I can't build the installer to test the config tool because I'm getting this error:
```
System.UnauthorizedAccessException: Access to the path '/.local/share/NuGet/Migrations' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at NuGet.Common.Migrations.MigrationRunner.GetMigrationsDirectory()
   at NuGet.Common.Migrations.MigrationRunner.Run()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
make: *** [Makefile:49: installer] Error 1
```

I think it's this issue:
https://github.com/dotnet/core/issues/7868

**Comment by rr-** [comment]
@walkawayy the tools builds are fixed in #820

**Review by rr- — APPROVED** [review]
LGTM but please test the config build if it works prior to merging.

**Review by lahm86 — APPROVED** [review]

**Comment by walkawayy** [comment]
Config tool works. Tested with the option disabled/enabled.

image

**Pull request merged**
