### PR TITLE
Implement 3D pickups

### LINKED ISSUE #1634: Add 3D PickUps
Cf TR1X

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1634.

### CODE REVIEW

**Review by lahm86 — COMMENTED** [review]
Really nice 🎉 

Just two things:
- Items rotate to Lara's rotation when she picks them up (for position testing). I believe this was addressed in TR1 by having a cleanup to reset the item's position again before leaving the function. It's in TR1's `Pickup_Collision`; in TR2 it's in `M_DoAboveWater` and `M_DoUnderwater` in `pickup.c`.
- Could we add the option to the config tool? I think it'll just need the equivalent from TR1 directly copied.

**Comment by rr-** [comment]
> Really nice 🎉
> 
> Just two things:
> 
> * Items rotate to Lara's rotation when she picks them up (for position testing). I believe this was addressed in TR1 by having a cleanup to reset the item's position again before leaving the function. It's in TR1's `Pickup_Collision`; in TR2 it's in `M_DoAboveWater` and `M_DoUnderwater` in `pickup.c`.

Fixed

> * Could we add the option to the config tool? I think it'll just need the equivalent from TR1 directly copied.

Added

Thanks.

**Comment by aredfan** [comment]
I found this one issue - the Talion pickup is half buried in the surface of Ice Palace.

**Review by lahm86 — APPROVED** [review]

**Review by walkawayy — APPROVED** [review]

**Comment by rr-** [comment]
@aredfan addressed, its position is better now, and the prayer wheels are happy as well. Sadly, this means it'll require rechecking everything from scratch.

CC @lahm86 @walkawayy

**Comment by aredfan** [comment]
The Talion is fixed. I've checked all of Lara's essentials and most keys/puzzles. The following items are buried partially.

- Shotgun, level 5
- Uzis, level 10
- Uzis clips, level 10
- M16, level 10
- Grenade Launcher, level 14
- Grenades, level 14
- Gong hammer, level 14
- Dragon Seal, level 15
- Circuit breaker, level 8

**Comment by rr-** [comment]
@aredfan just added another fix (courtesy of Lahm).
To make our lives easier I've also added the ability to repeatedly issue `/tp pickup` so that it'll cycle through all level pickups in round-robin fashion (will work for `/tp` in TR1 as well). Remember that we can now also cycle through command history with the up/down arrows, which makes it extra comfy.

**Comment by Richard-L** [comment]
I really regret I can't be more involved with testing these days as work is just busy, but I am following along and marvel at you guys' progress every day ❤️ 

This looks amazing.

**Review by aredfan — APPROVED** [review]
@rr- Thank you for making testing much more convenient all around. I've checked all the consumable items, then every key/puzzle type pickup in every level. Everything LGTM. 👍

**Review by lahm86 — APPROVED** [review]

**Pull request merged**
