### PR TITLE
inventory: animate passport at 60 fps

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Animates inventory in 60 FPS.

### CODE REVIEW

**Comment by rr-** [comment]
Regression found – fade effects cause wrong ring rotation times.

**Comment by rr-** [comment]
Should be now fixed

**Review by lahm86 — COMMENTED** [review]
Very nice :) Just a couple of things I noticed:

If Lara is in motion and you go into the inventory, the following happens:

https://github.com/LostArtefacts/TR1X/assets/33758420/920591d9-4e0c-4e65-9e6c-4868659b1b35

This doesn't happen in the pause screen, I can't remember if this was a problem before 60 fps was released that the original check [here](https://github.com/LostArtefacts/TR1X/pull/1315/files#diff-3a2072c29d493c7f4ec3dd662497c5afb11491c0143c4f941817c9e8b555f626) may have fixed.

One other thing is I think the inventory spins in too quickly on the title screen (both 30 and 60 fps) - as if it's jumping too far into the overall spin-out animation. This is the first visible frame

image

compared with current:

image

**Comment by lahm86** [comment]
Sorry, I didn't notice the update before the review above
Spin-in looks great now 👍

**Comment by rr-** [comment]
@lahm86 updated; I have also simplified `Interpolation_Enable` / `Interpolation_Disable` calls. This potentially could introduce regressions to rendering around phase boundaries (cutscene→level, level→inventory, pause→title screen etc.) and fade effects but hopefully not.

**Comment by lahm86** [comment]
I noticed the flicker is there on stats screens and also if you cancel/end a demo with fades enabled. But otherwise, transitions look good to me.

https://github.com/LostArtefacts/TR1X/assets/33758420/80da7843-be00-4f2d-b504-81879c20f5ce

**Comment by rr-** [comment]
@lahm86 fixed

**Comment by lahm86** [comment]
The stats screen looks good, but the flickering is still present in demo fade outs.

https://github.com/LostArtefacts/TR1X/assets/33758420/660a4a08-1452-422b-bcb6-047c9d152290

**Comment by rr-** [comment]
@lahm86 apologies – I was distracted and missed the second part of your comment; I have updated the build now.

**Review by lahm86 — APPROVED** [review]

**Comment by lahm86** [comment]
> @lahm86 apologies – I was distracted and missed the second part of your comment; I have updated the build now.

No problem, it's looking great 👍

**Pull request merged**
