### PR TITLE
Move /fly, /abortion and many type definitions to libtrx

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

https://github.com/LostArtefacts/libtrx/pull/33

### CODE REVIEW

**Comment by aredfan** [comment]
I found a small bug. When you use `/abortion` in Lara's Home, dynamite sprites will appear, this is probably because there's no explosion sprite present in the level.



In the latest dev snapshot (4.4-4-g451e619) these sprites are hidden from view.

**Comment by lahm86** [comment]
The dynamite sprite is in the explosion slot (151) in the level file, and this is also the case in Vilcabamba. Other levels like Caves don't have it at all.

**Review by walkawayy — APPROVED** [review]

**Comment by rr-** [comment]
@aredfan @lahm86 fixed. Explosions in levels that had missing sprites and sounds should now only appear when using cheats – the mummies should behave as they previously did.

**Comment by aredfan** [comment]
@rr- There's just 2 levels remaining that lack explosions for Lara, both are in the Egyptian segment of TRUB.

**Comment by rr-** [comment]
@aredfan fixed. Also tidied injections up a bit.

**Review by walkawayy — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
The explosions are working as expected in all 19 levels of TR1/UB. I've also checked to make sure the mummies are unaffected in this PR.  

LGTM, and thank you. 👍

**Review by lahm86 — APPROVED** [review]

**Pull request merged**
