### PR TITLE
inventory: fix demo timer

### LINKED ISSUE #1368: TR1X bug: Console command to enable 30/60 FPS on Main Menu, also triggers Demo Mode
**Dev snapshot:** 4.1.2-26-g7351e7c

______________________

When in 30 FPS mode, use the console command to switch to 60 FPS, and vice versa.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1368. This is an improvement to b276946f which didn't address the underlying issue. It also offers a small refactor to boost the readability.

https://nebula.wind.garden/serve/pub/TR1X-4.1.2-61-gc4dfb1b-Windows.zip

### CODE REVIEW

**Comment by walkawayy** [comment]
@aredfan could you check this test build out? Hopefully this issue is finally solved.

**Comment by aredfan** [comment]
> @aredfan could you check this test build out? Hopefully this issue is finally solved.

Of course!  I did a quick test and demo mode doesn't start when changing FPS modes.

One thing I noticed that's probably unrelated.  If you wait for the demo mode to start, the ring no longer closes and the backdrop doesn't fade out.

**Comment by rr-** [comment]
Thanks, good catch. Hopefully, this build should be free of issues.

https://nebula.wind.garden/serve/pub/TR1X-4.1.2-61-g9c6a569-Windows.zip

**Comment by aredfan** [comment]
> Thanks, good catch. Hopefully, this build should be free of issues.
> 
> https://nebula.wind.garden/serve/pub/TR1X-4.1.2-61-g9c6a569-Windows.zip

Yep that fixed the issue, thank you.  Tested again and everything LGTM.

**Review by walkawayy — APPROVED** [review]
LGTM! Didn't see the issue while testing a bunch.

**Review by lahm86 — APPROVED** [review]

**Pull request merged**
