### PR TITLE
savegame: fix effect crash

### LINKED ISSUE #746: Crash when loading a save with spaz_effect_count set
If the game is saved while Lara is in the following animation and then reloaded, a crash occurs. This is present in TombATI as well as T1M (found by Radgryd during randomizer testing).

20230304_144736_Atlantis_6

Saving during Lara's normal animation doesn't lead to a crash.
20230304_144737_Atlantis

The cause I think is that while `spaz_effect_count` and `spaz_effect` are [saved](https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/savegame/savegame_bson.c#L1065), only `spaz_effect_count` is [restored](https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/savegame/savegame_bson.c#L712).

The crash seems to occur below as `g_Lara.spaz_effect_count` is used in the condition, but `g_Lara.spaz_effect` is assumed to be set.

https://github.com/LostArtefacts/Tomb1Main/blob/develop/src/game/lara/lara_control.c#L158

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #746.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This will restore the explosion effect on load that puts Lara into the state in question, provided that enhanced saves are enabled (otherwise there won't be an effect to reference). With enhanced saves off, and for legacy saves, the guard in `lara_control.c` avoids the null pointer issue previously seen.

A short demo of the fix in action can be seen at https://www.youtube.com/watch?v=7H3evEL6Qgk - both the effect and Lara's stance are restored on load.

### CODE REVIEW

**Comment by rr-** [comment]
I think this should become 2.13.2 shouldn't it?

**Comment by lahm86** [comment]
> I think this should become 2.13.2 shouldn't it?

Sounds good, although I think it's a very rare bug as you need to have saved on exactly the right frame. Maybe a bug fix release along with the fix for #748 once that's in and verified?

**Comment by walkawayy** [comment]
> > I think this should become 2.13.2 shouldn't it?
> 
> Sounds good, although I think it's a very rare bug as you need to have saved on exactly the right frame. Maybe a bug fix release along with the fix for #748 once that's in and verified?

I agree this is a super rare bug that's been in place since the original game. But since we need a hotfix for the AMD GPU depth buffer issue, we can probably release this fix alongside it in 2.13.2.

**Review by walkawayy — APPROVED** [review]

**Comment by rr-** [comment]
Cherry-picked by hand to the `stable` branch.

**Pull request closed without merging**
