### PR TITLE
output: do not rely on FPS for fades

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Preparation for 60 FPS.

### CODE REVIEW

**Review by walkawayy — COMMENTED** [review]
All fades seem to work fine except the fade out from the gym. It's just a black screen with no fade. On current develop, it fades out.

**Comment by rr-** [comment]
Both are working fine for me – with the level skip and with the swimming pool way.

**Comment by walkawayy** [comment]
> Both are working fine for me – with the level skip and with the swimming pool way.

You are right. After our talks on Discord, I made sure I wasn't holding any inputs. I must have been skipping the fade.

**Review by walkawayy — APPROVED** [review]

**Comment by walkawayy** [comment]
Worth checking out #1228. I think there is in fact some kind of lagg happening when a fade is skipped.

**Comment by rr-** [comment]
The last commits resolve #1228 which are a regression in develop.

**Pull request merged**
