### PR TITLE
data: switch from WEBP to JPEG

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

The files appear identical visually, but the title menu loads much faster with this format. On my machine it goes down from 236 ms to around 150 ms. However, this bloats the asset size by 34% (9.4 MiB compared to 7.0 MiB).

### CODE REVIEW

**Review by walkawayy — COMMENTED** [review]
Looks good except you missed the title, credits, and Eidos images in the UB gameflow file.

**Review by walkawayy — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
LGTM.

**Review by lahm86 — APPROVED** [review]

**Comment by rr-** [comment]
With the recent improvements on develop and #1470 the savings of this pull request went down to 15 milliseconds (130 ms vs 115 ms). I'll hold on for a bit longer to see if we can do better on other fronts prior to making this switch.

**Comment by rr-** [comment]
All in all I don't think it's worth it anymore as the savings aren't so dramatic with the recent improvements on develop – especially considering the file size increase. Closing for now.

**Pull request closed without merging**
