### PR TITLE
lara: fix empty holsters when starting level with shotgun equipped

### LINKED ISSUE #749: T1M bug: Holsters are empty when starting a new level if shotgun is equipped beforehand
Whether Lara has pistols, magnums or uzis holstered - each of these will disappear when starting a new level *if* the shotgun is equipped beforehand i.e. the shotgun is the weapon Lara draws.

**End of Lost Valley:**
20230307_161153_Lost_Valley
**Beginning of Tomb of Qualopec:**
20230307_161200_Tomb_of_Qualopec

The outcome is the same whether "Pistols as primary weapon" is enabled or disabled.

In TombATI, pistols will always appear in Lara's holsters when starting a new level no matter which weapon is holstered or equipped beforehand.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #749.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed empty holsters when starting a level with the shotgun equipped.
...

### CODE REVIEW

**Comment by lahm86** [comment]
If I start a new game, Lara's pistols aren't drawn at all, and equally when you go to the next level - they only show when you go to the next level with the shotgun equipped. It also seems to lose the magnums/uzis being drawn if they were the last gun used but you finish the level without them equipped.

20230312_151042_Caves

**Comment by walkawayy** [comment]
Oops try that if you can.

**Review by lahm86 — APPROVED** [review]
That's working great now.

**Comment by rr-** [comment]
I'm pretty sure this breaks something...

Tests I can think of that need to be done prior to merging:

- [x] Start a new game, Lara should have pistols in her holsters
- [x] Start Gym, Lara should have the gym outfit without the holsters
- [x] Draw pistols. Go to the next level. Lara should keep her guns and have empty holsters
- [x] Draw pistols, unequip them. Go to the next level. Lara should have nothing in her hands, and the pistols in her holsters
- [ ] Draw uzis, then switch to shotgun. Go to the next level. Lara should have the shotgun in her hands and uzis in her holsters, and no shotgun on the back
- [ ] Draw uzis, then switch to the shotgun, then unequip the shotgun. Go to next level. Lara should have nothing in her hands, uzis in her holsters and shotgun on her back
- [x] Draw pistols. Save, load. Lara should keep her pistols and have empty holsters
- [x] Draw pistols, unequip them. Save, load. Lara should have nothing in her hands and pistols in her holsters
- [x] Draw uzis, then switch to shotgun. Save, load. Lara should have the shotgun in her hands and uzis in her holsters, and no shotgun on the back.
- [x] Draw uzis, then switch to shotgun, then unequip the shotgun. Save, load. Lara should have nothing in her hands, uzis in her holsters and shotgun on her back.
- [x] Repeat the "go to the next level" tests if there's a cutscene level in between.
- [x] Play with load game → select level if it doesn't do anything crazy.

**Comment by walkawayy** [comment]
Ok most of the test scenarios worked, and I also tested Natla's Mines and the guns / meshes were correctly removed.

The only failure involves a non pistol weapon in the holsters while the shotgun is equipped. When the next level loads, Lara has the shotgun equipped, but the pistols are in the holsters. I was gonna check OG behavior to see how the game remembered the previous gun mesh in the holster, but the OG game always reverts to pistols on a new level. So I'm not really sure it's a bug?

**Comment by rr-** [comment]
If everything else works I think that's dismissable.
Now that I think of it I don't think we store the information needed to restore the alternate weapon holster meshes anyway?

**Comment by walkawayy** [comment]
> If everything else works I think that's dismissable. Now that I think of it I don't think we store the information needed to restore the alternate weapon holster meshes anyway?

Ya we don't have any way to tell afaik. But maybe @lahm86 can confirm.

**Comment by lahm86** [comment]
> > If everything else works I think that's dismissable. Now that I think of it I don't think we store the information needed to restore the alternate weapon holster meshes anyway?
> 
> Ya we don't have any way to tell afaik. But maybe @lahm86 can confirm.

I agree - I don't think it's currently a feature. You'd have to store the last two gun types I think?

**Comment by rr-** [comment]
Yeah but I don't think it needs to be tackled in this ticket if at all due to the amount of changes that'd need.

**Comment by rr-** [comment]
If there are no other issues, this PR can be squashed and merged.

**Pull request merged**
