### PR TITLE
Decompile light calculations, OG cheats, texture animations and underwater wibble

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

#1693

### CODE REVIEW

**Comment by lahm86** [comment]
Bartoli's Hideout crashes on load. Potentially something to do with the sunset effect in this level? `light_mode` is 3 for this effect, and it's the only level that uses it. Still looking into it, but it's on the second frame, and room 102 specifically, vertex 0 where it crashes.

`libtrx/log_windows.c 58 M_StackTrace 00. 0x5fa137af: (/app/build/tr2/win/game/output.c:1066:27) Output_LightRoom`

**Comment by aredfan** [comment]
The OG cheats seem to have no effect. I've tried this routine; walk forward, walk back, 3 turns, jump forward/back, while holding pistols or a flare.

Apart from the crash mentioned by Lahm, everything else LGTM.

**Comment by rr-** [comment]
@aredfan @lahm86 fixed

**Review by lahm86 — APPROVED** [review]
LGTM

**Pull request merged**
