### PR TITLE
Move TR1 FMV player to libtrx and update TR2 to use it

### LINKED ISSUE #1729: Improve TR2 FMV cutscene rendering
The OG renders black scanlines for every other pixel row, and also switches the screen size back and forth even for the windowed mode.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1729.

Needs both TR1 and TR2 to be tested, particularly for potentially nasty scenarios like alt-tabbing, taking screenshots, or trying to use the console during playback. TR2 testing should also cover both software and hardware renderers, as well as fullscreen and windowed modes, since each has a significantly different implementation.

### CODE REVIEW

**Comment by lahm86** [comment]
TR1 looks fine, no issues there that I can see.

For TR2, I can hear the FMVs but see only a black screen.

**Comment by rr-** [comment]
> TR1 looks fine, no issues there that I can see.
> 
> For TR2, I can hear the FMVs but see only a black screen.

Thanks. Which rendering settings are you using?

**Comment by lahm86** [comment]
> > TR1 looks fine, no issues there that I can see.
> > For TR2, I can hear the FMVs but see only a black screen.
> 
> Thanks. Which rendering settings are you using?

Sorry, I didn't provide more detail before. This is my current config. Changing to full screen, I can't run the game at all (I have a 1440p monitor, and changing the resolution to 1080 doesn't help there - my guess is that's a DirectX issue which the older games suffer from).

image

**Comment by rr-** [comment]
@lahm86 can you please check now?

**Review by lahm86 — APPROVED** [review]

**Comment by lahm86** [comment]
> @lahm86 can you please check now?

Thanks, everything looks good. Tried alt-tabbing, alt-F4, console, shifting the window around and couldn't find any problems.

**Comment by aredfan** [comment]
TR1X and TR2X issue:

- [x] It's possible to open the console during FMVs but it isn't visible. This doesn't happen in the latest TR1X dev snapshot.

TR2X issues:

- [x] Fullscreen - the game crashes after the second intro FMV.

My setup:

Screenshot

**Comment by Richard-L** [comment]
I had thought FMVs being invisible in TR2X is just a normal consequence of the game not being fully decompiled yet, and according issues on that wouldn't be welcome. But I see you've been working on FMVs, so maybe I'm just slow to connect the dots hah.

When you say "try now", is it possible for me to go somewhere within Github to update a windows build for myself somehow? Can also discuss this on discord.

**Comment by rr-** [comment]
@aredfan addressed both issues.

@Richard-L you can find PR builds in the build details → details (any job) → summary → relevant zip files.

**Review by aredfan — APPROVED** [review]
> @aredfan addressed both issues.

Both issues are fixed, thank you. 👍

**Pull request merged**
