### PR TITLE
config: move enable_game_modes to config and add gameflow override

### LINKED ISSUE #962: Move enable_game_modes option from gameflow to config tool

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #962.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Moved the `enable_game_modes` option from the gameflow to the config tool.

### CODE REVIEW

**Comment by walkawayy** [comment]
Requesting @ajtudela for a translation please. :)

Also for the future:

"Enable save crystals"
"Description": "Limits saving to the beginning of levels save crystals. Levels have limited, single use save crystals like the PS1 version. Changing this option will require restarting the level."

**Comment by rr-** [comment]
This is a breaking change; level builders now can't turn this feature off.

IMO it should be present in both config and gameflow so that the level can choose if they want to support this feature and the user can choose if they can go with that.

**Comment by ajtudela** [comment]
> Requesting @ajtudela for a translation please. :)
> 
> Also for the future:
> 
> "Enable save crystals" "Description": "Limits saving to the beginning of levels save crystals. Levels have limited, single use save crystals like the PS1 version. Changing this option will require restarting the level."

Done!

**Review by lahm86 — COMMENTED** [review]
Looks good, the only thing is that if `override_game_modes` is missing, the script doesn't load. Obviously not an issue for new installs, but should we make it default to `false` for any older gameflows out there (TRLEs mainly I suppose)? Or should it be the standard going forward that it must be included? I appreciate that's a bit of a breakaway from the other settings loaded in the gameflow, just though I'd mention it.

**Comment by walkawayy** [comment]
> Looks good, the only thing is that if `override_game_modes` is missing, the script doesn't load. Obviously not an issue for new installs, but should we make it default to `false` for any older gameflows out there (TRLEs mainly I suppose)? Or should it be the standard going forward that it must be included? I appreciate that's a bit of a breakaway from the other settings loaded in the gameflow, just though I'd mention it.

Ya I realized that but tried to match all other gameflow options. I think it's ok to default to `false` though since it's not a required option. I'll change that.

**Review by lahm86 — APPROVED** [review]

**Review by rr- — COMMENTED** [review]
On Discord we mentioned that setting the override property to false would disable the game modes and it would be a null value or an absence of this property altogether that would have no effect on the menus. With the current implementation I think it's better to call it `force_disable_gamemodes`, or alternatively implement the above approach. WDYT?

**Comment by walkawayy** [comment]
Yes good point. The name is a little clunky. I was hesitant to use disable because the new game plus menu options (in a future PR) will be available. So it's only for the first playthrough. I'll push up a change with a rename to `disable_game_modes` and the comment in the json should be enough to explain that it works only for the first playthrough.

**Review by rr- — APPROVED** [review]

**Pull request merged**
