### PR TITLE
FMV: Tie FMV audio to sound volume

### LINKED ISSUE #1110: Feature request/Enhancement: Have a way to control FMV volume.
Currently, in TR1X there is no way to control the volume for FMV cutscenes, and the game defaults to playing the FMV volume at SDL_MIX_MAXVOLUME. Which isn't ideal.

---

**Possible solutions:**

- Tie the FMV audio to one the pre-existing sliders (this is what I personally did in my build of the game).
- Create a new volume slider specifically for FMV's.

### PR DESCRIPTION
**Pull request by Oplexitie**
Resolves #1110.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

I tied the FMV audio volume to the sound volume by replacing `SDL_MIX_MAXVOLUME` with `g_Config.sound_volume * 12`.
This was done to have `audio_volume`'s max value be as close to `SDL_MIX_MAXVOLUME` while not sounding too loud.

### CODE REVIEW

**Comment by rr-** [comment]
Hi, thanks for the pull request. We should avoid the `* 12` magic constant. Currently it's hard to do this as samples and music each use different volume internally, and `MAX_VOLUME` is now defined in `option_sound.c` (eg UI code) while it should be the audio routines that provide this value. As such I propose introducing a few getter functions:

```patch
diff --git a/src/game/music.c b/src/game/music.c
index b8c45f05..f557a31a 100644
--- a/src/game/music.c
+++ b/src/game/music.c
@@ -168,6 +168,11 @@ void Music_StopTrack(MUSIC_TRACK_ID track)
     }
 }
 
+int16_t Music_GetVolume(void)
+{
+    return m_MusicVolume * Music_GetMaxVolume();
+}
+
 void Music_SetVolume(int16_t volume)
 {
     m_MusicVolume = volume ? (25 * volume + 5) / 255.0f : 0.0f;
@@ -176,6 +181,16 @@ void Music_SetVolume(int16_t volume)
     }
 }
 
+int16_t Music_GetMinVolume(void)
+{
+    return 0;
+}
+
+int16_t Music_GetMaxVolume(void)
+{
+    return 10;
+}
+
 void Music_Pause(void)
 {
     if (m_AudioStreamID < 0) {
diff --git a/src/game/music.h b/src/game/music.h
index 9dc789b0..5fe52e6b 100644
--- a/src/game/music.h
+++ b/src/game/music.h
@@ -26,9 +26,18 @@ void Music_Stop(void);
 // Stops the provided single track and restarts the looped track if applicable.
 void Music_StopTrack(MUSIC_TRACK_ID track);
 
-// Sets the game volume. Value can be 0-255.
+// Gets the game volume.
+int16_t Music_GetVolume(void);
+
+// Sets the game volume. Value can be 0-10.
 void Music_SetVolume(int16_t volume);
 
+// Gets the minimum possible game volume.
+int16_t Music_GetMinVolume(void);
+
+// Gets the maximum possible game volume.
+int16_t Music_GetMaxVolume(void);
+
 // Pauses the music.
 void Music_Pause(void);
 
diff --git a/src/game/option/option_sound.c b/src/game/option/option_sound.c
index 84f954c5..6bebac0f 100644
--- a/src/game/option/option_sound.c
+++ b/src/game/option/option_sound.c
@@ -11,9 +11,6 @@
 #include <stdbool.h>
 #include <stdio.h>
 
-#define MIN_VOLUME 0
-#define MAX_VOLUME 10
-
 typedef enum SOUND_TEXT {
     TEXT_MUSIC_VOLUME = 0,
     TEXT_SOUND_VOLUME = 1,
@@ -98,7 +95,7 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
 
     switch (g_OptionSelected) {
     case TEXT_MUSIC_VOLUME:
-        if (g_Input.menu_left && g_Config.music_volume > MIN_VOLUME) {
+        if (g_Input.menu_left && g_Config.music_volume > Music_GetMinVolume()) {
             g_Config.music_volume--;
             g_IDelay = true;
             g_IDCount = 10;
@@ -107,7 +104,9 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
             sprintf(buf, "| %2d", g_Config.music_volume);
             Text_ChangeText(m_Text[TEXT_MUSIC_VOLUME], buf);
             Config_Write();
-        } else if (g_Input.menu_right && g_Config.music_volume < MAX_VOLUME) {
+        } else if (
+            g_Input.menu_right
+            && g_Config.music_volume < Sound_GetMaxVolume()) {
             g_Config.music_volume++;
             g_IDelay = true;
             g_IDCount = 10;
@@ -118,9 +117,9 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
             Config_Write();
         }
 
-        if (g_Config.music_volume == MIN_VOLUME) {
+        if (g_Config.music_volume == Music_GetMaxVolume()) {
             Text_Hide(m_Text[TEXT_LEFT_ARROW], true);
-        } else if (g_Config.music_volume == MAX_VOLUME) {
+        } else if (g_Config.music_volume == Sound_GetMaxVolume()) {
             Text_Hide(m_Text[TEXT_RIGHT_ARROW], true);
         } else {
             Text_Hide(m_Text[TEXT_LEFT_ARROW], false);
@@ -130,7 +129,7 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
         break;
 
     case TEXT_SOUND_VOLUME:
-        if (g_Input.menu_left && g_Config.sound_volume > MIN_VOLUME) {
+        if (g_Input.menu_left && g_Config.sound_volume > Sound_GetMinVolume()) {
             g_Config.sound_volume--;
             g_IDelay = true;
             g_IDCount = 10;
@@ -139,7 +138,9 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
             sprintf(buf, "} %2d", g_Config.sound_volume);
             Text_ChangeText(m_Text[TEXT_SOUND_VOLUME], buf);
             Config_Write();
-        } else if (g_Input.menu_right && g_Config.sound_volume < MAX_VOLUME) {
+        } else if (
+            g_Input.menu_right
+            && g_Config.sound_volume < Sound_GetMaxVolume()) {
             g_Config.sound_volume++;
             g_IDelay = true;
             g_IDCount = 10;
@@ -150,9 +151,9 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
             Config_Write();
         }
 
-        if (g_Config.sound_volume == MIN_VOLUME) {
+        if (g_Config.sound_volume == Sound_GetMinVolume()) {
             Text_Hide(m_Text[TEXT_LEFT_ARROW], true);
-        } else if (g_Config.sound_volume == MAX_VOLUME) {
+        } else if (g_Config.sound_volume == Sound_GetMaxVolume()) {
             Text_Hide(m_Text[TEXT_RIGHT_ARROW], true);
         } else {
             Text_Hide(m_Text[TEXT_LEFT_ARROW], false);
diff --git a/src/game/sound.c b/src/game/sound.c
index bc899099..14a08669 100644
--- a/src/game/sound.c
+++ b/src/game/sound.c
@@ -540,6 +540,21 @@ void Sound_SetMasterVolume(int8_t volume)
     m_MasterVolume = raw_volume & 0x3F;
 }
 
+int8_t Sound_GetMasterVolume(void)
+{
+    return (m_MasterVolume - 3) / 6;
+}
+
+int32_t Sound_GetMinVolume(void)
+{
+    return 0;
+}
+
+int32_t Sound_GetMaxVolume(void)
+{
+    return 10;
+}
+
 void Sound_ResetAmbient(void)
 {
     Sound_ResetAmbientLoudness();
diff --git a/src/game/sound.h b/src/game/sound.h
index 929a040d..0f9cb4a2 100644
--- a/src/game/sound.h
+++ b/src/game/sound.h
@@ -16,7 +16,10 @@ void Sound_StopAmbientSounds(void);
 void Sound_PauseAll(void);
 void Sound_UnpauseAll(void);
 void Sound_StopAllSamples(void);
+int8_t Sound_GetMasterVolume(void);
 void Sound_SetMasterVolume(int8_t volume);
+int32_t Sound_GetMinVolume(void);
+int32_t Sound_GetMaxVolume(void);
 void Sound_LoadSamples(
     size_t num_samples, const char **sample_pointers, size_t *sizes);
 void Sound_ResetAmbient(void);
diff --git a/src/specific/s_fmv.c b/src/specific/s_fmv.c
index 0156615d..8a1f5d55 100644
--- a/src/specific/s_fmv.c
+++ b/src/specific/s_fmv.c
@@ -28,6 +28,7 @@
 #include "game/input.h"
 #include "game/screen.h"
 #include "game/shell.h"
+#include "game/sound.h"
 #include "gfx/2d/2d_renderer.h"
 #include "gfx/2d/2d_surface.h"
 #include "gfx/context.h"
@@ -303,6 +304,13 @@ static const struct TextureFormatEntry {
     { AV_PIX_FMT_NONE, SDL_PIXELFORMAT_UNKNOWN },
 };
 
+static int S_FMV_GetAudioVolume(void)
+{
+    const double volume_dbl = (g_Config.sound_volume - Sound_GetMinVolume())
+        / (double)Sound_GetMaxVolume();
+    return volume_dbl * SDL_MIX_MAXVOLUME;
+}
+
 static int S_FMV_PacketQueuePutPrivate(PacketQueue *q, AVPacket *pkt)
 {
     MyAVPacketList pkt1;
@@ -2166,7 +2174,7 @@ static VideoState *S_FMV_StreamOpen(const char *filename)
     S_FMV_InitClock(&is->audclk, &is->audioq.serial);
     S_FMV_InitClock(&is->extclk, &is->extclk.serial);
     is->audio_clock_serial = -1;
-    is->audio_volume = g_Config.sound_volume * 12;
+    is->audio_volume = S_FMV_GetAudioVolume();
     is->av_sync_type = AV_SYNC_AUDIO_MASTER;
     is->read_tid = SDL_CreateThread(S_FMV_ReadThread, "read_thread", is);
     if (!is->read_tid) {
@@ -2236,7 +2244,7 @@ static void S_FMV_EventLoop(VideoState *is)
         case SDL_WINDOWEVENT:
             switch (event.window.event) {
             case SDL_WINDOWEVENT_FOCUS_GAINED:
-                is->audio_volume = g_Config.sound_volume * 12;
+                is->audio_volume = S_FMV_GetAudioVolume();
                 break;
 
             case SDL_WINDOWEVENT_FOCUS_LOST:
```

Also it's a user-facing change and thus we're missing a changelog entry:

```patch
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 3b3b220b..5e1a3883 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -3,6 +3,7 @@
 - added the restart level option to the passport in save crystal mode (#1099)
 - changed `force_enable_save_crystals` to `force_save_crystals` for custom level authors to force enable or disable the save crystals setting (#1102)
 - changed `force_disable_game_modes` to `force_game_modes` for custom level authors to force enable or disable the game modes setting (#1102)
+- fixed FMVs always playing at 100% volume – now they'll play at the game sound volume (#1110)
 - fixed bugs when trying to stack multiple movable blocks (#1079)
 - fixed Lara's meshes being swapped in the gym level when using the console to give guns (#1092)
 - fixed Midas's touch having unrestricted vertical range (#1094)
```

**Comment by Oplexitie** [comment]
Hello, in retrospect, I'd like to apologize for my pull request, what I posted should have been more like the code you posted, and not just the slapdash fix I used for my build.

After looking at your code, I agree with these changes, and made a push implementing them.
Although I did make a few a tweaks to `S_FMV_GetAudioVolume(void)` :

```
const float volume_dbl = g_Config.sound_volume / (float)Sound_GetMaxVolume();
```
I switched `volume_dbl` and `Sound_GetMaxVolume()` from double to float. I made this change since I did not think the extra precision was needed.

And I also removed  `Sound_GetMinVolume()`. `Sound_GetMinVolume()` subtracting from `g_Config.sound_volume` didn't seem to contribute anything to the calculation, due to `Sound_GetMinVolume()` always returning 0.

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
Apart from small warnings from the linter, LGTM

**Review by lahm86 — COMMENTED** [review]
LGTM (other than `make lint` needed).

I do however wonder if it makes more sense to tie FMV audio to `g_Config.music_volume` rather than `g_Config.sound_volume`. IMO, the track/ambience/cutscene audio control feels more related to FMV audio than the SFX control.

**Comment by Oplexitie** [comment]
Ok, so `make lint` should be good. Kind of hope I didn't screw something up with my initial make lint commit.

As for tying the FMV Audio to `g_Config.music_volume` instead of `g_Config.sound_volume`. I gave it some thought, and while it might make more sense, I believe there are more players that would turn off the music while still wanting the FMV Audio, than the other option. Also, while there is music in the FMV cutscenes, I feel like that the sounds (such has speech and sfx) play a bigger and more important role in them.

**Comment by rr-** [comment]
Agreed, maybe we should tie FMV to sound instead?

**Comment by walkawayy** [comment]
Should we just add a third volume slider for FMV sound level? I agree with Lahm that it makes sense to tie it to music, but I can also see the point about people disabling music.

**Comment by Oplexitie** [comment]
Adding a third slider would solve the issue, but since each slider is represented by an icon, we would need to add a new icon to the game. At least, if we want to stay consistent.

**Comment by rr-** [comment]
A third slider sounds good as well, for now I'd tie it to sound volume as part of this PR and then create a new feature request to control the volume of FMVs with a separate slider as it's significantly more development effort.

**Review by walkawayy — APPROVED** [review]

**Pull request merged**
