### PR TITLE
Fix inventory ring shutdown

### LINKED ISSUE #1460: Issuing a gameflow command when having an item selected results in glitches
Similar to the issues found when adding `/demo`, `/play`, etc., in TR2X in LostArtefacts/TR2X#161, TR1X experiences a problem where the inventory fails to properly shut down in certain situations. This occurs when the player selects an item, such as the controls dialog, and then uses the console to issue a command like `/demo` or `/play`. The camera angles become distorted, and dialogs do not clear correctly.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1460.
https://home.wind.garden/serve/pub/TR1X-4.3-13-g22b47d9-Windows.zip

### CODE REVIEW

**Review by walkawayy — APPROVED** [review]

**Comment by aredfan** [comment]
I found a crash that happens with these steps.

1. Select Load Game/New Game/Exit Game
2. Execute `/demo` or `/play`
3. Load a savegame

**Comment by rr-** [comment]
@aredfan fixed:
https://home.wind.garden/serve/pub/TR1X-4.3-13-g93b0a0a-Windows.zip

**Comment by aredfan** [comment]
> @aredfan fixed: https://home.wind.garden/serve/pub/TR1X-4.3-13-g93b0a0a-Windows.zip

Thank you. The crash is gone and the commands doesn't cause glitches on the main menu.

I did find this minor issue when following the same steps for the in-game inventory e.g. the compass, and execute demo/play there. The inventory text at the top and the gold arrows carry over to the demo or the following level.

**Comment by rr-** [comment]
@aredfan fixed: https://home.wind.garden/serve/pub/TR1X-4.3-13-gaa94fe6-Windows.zip

**Review by aredfan — APPROVED** [review]
The inventory text and arrows issue is resolved. I've tested all the scenarios I could think of relating to the main menu, inventory, quick save and quick load.

LGTM. 👍

**Pull request merged**
